package com.nploetz049.athena.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF714da0)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFefdbff)
val md_theme_light_onPrimaryContainer = Color(0xFF290056)
val md_theme_light_secondary = Color(0xFF645a6f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFebddf6)
val md_theme_light_onSecondaryContainer = Color(0xFF20182a)
val md_theme_light_tertiary = Color(0xFF80525a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9df)
val md_theme_light_onTertiaryContainer = Color(0xFF321018)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbfc)
val md_theme_light_onBackground = Color(0xFF1d1b1e)
val md_theme_light_surface = Color(0xFFfffbfc)
val md_theme_light_onSurface = Color(0xFF1d1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe8dfeb)
val md_theme_light_onSurfaceVariant = Color(0xFF4a454e)
val md_theme_light_outline = Color(0xFF7b757e)
val md_theme_light_inverseOnSurface = Color(0xFFf5eff3)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inversePrimary = Color(0xFFdab9ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFdab9ff)
val md_theme_dark_onPrimary = Color(0xFF401b6d)
val md_theme_dark_primaryContainer = Color(0xFF583486)
val md_theme_dark_onPrimaryContainer = Color(0xFFefdbff)
val md_theme_dark_secondary = Color(0xFFcfc2da)
val md_theme_dark_onSecondary = Color(0xFF352d40)
val md_theme_dark_secondaryContainer = Color(0xFF4c4357)
val md_theme_dark_onSecondaryContainer = Color(0xFFebddf6)
val md_theme_dark_tertiary = Color(0xFFf2b8c1)
val md_theme_dark_onTertiary = Color(0xFF4b252d)
val md_theme_dark_tertiaryContainer = Color(0xFF653b43)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9df)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b1e)
val md_theme_dark_onBackground = Color(0xFFe7e1e6)
val md_theme_dark_surface = Color(0xFF1d1b1e)
val md_theme_dark_onSurface = Color(0xFFe7e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF4a454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFccc4cf)
val md_theme_dark_outline = Color(0xFF958e99)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe7e1e6)
val md_theme_dark_inversePrimary = Color(0xFF714da0)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF371b5a)
val error = Color(0xFFba1b1b)